### ISSUE TITLE
As a user I want to be able to edit a single text file that's stored on a server

### ISSUE THREAD

**Issue by JonasNorlinder** [rehnarama/MALTE#1]
This includes:
- [x] Creating the editor frontend #27 
- [x] Establish WebSocket connection between server and client #28 
- [x] Expose a file as a in-memory buffer from the backend to the frontend via the WebSocket connection #29
- [x] Establish a set of commands (insert/remove) that is sent to/from the server between clients that is applied to the buffer #30
- [x] Periodically save the in-memory buffer back to the file system
