### ISSUE TITLE
As an owner I want to be able to invite people using user accounts

### ISSUE THREAD

**Issue by noler** [rehnarama/MALTE#10]
- [x] Store users in a database #135 
 - [x] Login page #150
 - [x] Be able to add pre-approved users, i.e. accepted on first successful login #158
- [x] First time login setup #143
- [x] Add authentication scheme for WebSocket connections
