### ISSUE TITLE
As a user I want a terminal window in which I can run commands within the project

### ISSUE THREAD

**Issue by JonasNorlinder** [rehnarama/MALTE#6]
Used https://shapeshed.com/command-line-utilities-with-nodejs/#piping-data to see how you can pipe in Node

- [x] Spawn shell and pipe data to browser #32 
- [x] Apply the data seen in the server to the xterm.js terminal emulator #33
- [x] Send user input to the server terminal emulator, apply it to shell stdin #34
