### ISSUE TITLE
As a user I want a visual representation of the files in the project

### ISSUE THREAD

**Issue by JonasNorlinder** [rehnarama/MALTE#7]
This includes
- [x] On the backend, send all files in the project root over the websocket connection #37 
- [x] Create a tree frontend component which be can be used to display files #38
- [x] Integrate the file data sent from backend with the frontend tree component #39
- [x] Watch the filesystem for external changes and re-submit files to frontend #40
